import React from 'react';
import {
  FaMobileAlt,
  FaKey,
  FaLock,
  FaFingerprint,
} from 'react-icons/fa';
import './MFAModesPage.css';

const MFAModesPage = () => {
  return (
    <div className="mfa-page">
      <h2 className="mfa-title">MFA Modes</h2>
      <p className="mfa-subtitle">
        Use multi-factor authentication (MFA) to add an extra layer of security to your account.
      </p>

      <div className="mfa-grid">
        <div className="mfa-card large">
          <div className="mfa-icon-wrapper large-icon">
            <FaMobileAlt size={50} />
          </div>
          <div className="mfa-info">
            <h3>TSAR OneAuth</h3>
            <p>Use our own authenticator app to experience a hassle-free passwordless sign-in.</p>
            <div className="mfa-actions">
              <button className="mfa-btn">Set up Now</button>
              <a href="#" className="mfa-link">Learn more</a>
            </div>
          </div>
        </div>

        <div className="mfa-card">
          <div className="mfa-icon-wrapper">
            <FaLock size={32} />
          </div>
          <div className="mfa-info">
            <h3>OTP Authenticator</h3>
            <p>Use time-based OTPs generated by authenticator apps to securely sign in to your TSAR account.</p>
            <a href="#" className="mfa-link">Set up Now</a>
          </div>
        </div>

        <div className="mfa-card">
          <div className="mfa-icon-wrapper">
            <FaKey size={32} />
          </div>
          <div className="mfa-info">
            <h3>Security Key</h3>
            <p>Configure and use a hardware security key for additional verification during sign-in.</p>
            <a href="#" className="mfa-link">Set up Now</a>
          </div>
        </div>

        <div className="mfa-card">
          <div className="mfa-icon-wrapper">
            <FaFingerprint size={32} />
          </div>
          <div className="mfa-info">
            <h3>Passkey</h3>
            <p>Set up a passkey for your TSAR account using your device and enjoy secure passwordless sign-in.</p>
            <a href="#" className="mfa-link">Set up Now</a>
          </div>
        </div>
      </div>
    </div>
  );
};

export default MFAModesPage;
